### ISSUE TITLE
Partial/lightweight participation

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#11]
We can define downloading and pinning the entire index (but not the full blockchain, or referenced journal entries) as a "standard" participation level. However, clients may wish to participate without having to download anything, fully on the trust of a Peer.

This is an optimization, but a fairly important one for making the system accessible those unable or unwilling to put up resources to run a full node.

This may also be related to the more broad idea of fragmented participation, where nodes interested in e.g. music industry may not care about data from the library world and vice versa.

Some possible solutions:
### Peer trusted API

Peers could accept transactions through a REST API with some means of authentication of their choice, so users (internal or authed external) of an organization running a Peer node can submit writes without going through the full p2p network. This is probably a core feature. Client nodes would have something similar, as well.
### "Trusting" bootstrap

Client nodes can probably bootstrap by downloading just a truncated head of the blockchain (probably just the latest block, at the beginning)
### Non-retrention/FIFO local block store

Blocks don't need to be stored locally; they can be discarded after verification, only keeping the hash
### Many mediachains

Fully independent journals for different industries or groups. Objects may still make references to members of other chains because of the IPFS addressing [SEPARATE DISCUSSION]

**Comment by parkan** [comment]
@bigs @vyzo

**Comment by vyzo** [comment]
I think we should aim to make it easy to run a node in a $10/month public cloud instance -- this gives you 24GB SSD in linode and probably something similar in digital ocean.

So we have to factor sharding in the design from the start. A node can only verify transactions for chains in its shards -- inserts can be verified from the store, so you can have them mixed in a block from a different shard.
We can start with a single blockchain and bigger nodes running all shards, and we can split to a blockchain per shard later on when it becomes a scaling bottleneck.

We should monitor the blockchain with metrics closely, so that we know when it is time to shard!

**Comment by muneeb-ali** [comment]
Are you talking about cryptocurrency blocks or mediachain blocks (sorry I'm not that familiar with mediachain yet)?

**Comment by parkan** [comment]
@muneeb-ali mediachain "journal" blocks, see https://github.com/mediachain/mediachain/blob/master/rfc/mediachain-rfc-2.md#the-journal-blockchain

**Comment by parkan** [comment]
This is supported naturally by PII design, closing
