### ISSUE TITLE
Define shared protobuf types

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain#18]
In parallel to work here https://github.com/mediachain/L-SPACE/pull/67/files

~~I was thinking that we should probably define the "interchange"/wire types (particularly the `ChainCell`s) as shared protobuf defs. However, this inheritance model looks a little cumbersome. As far as I can tell, the best practice is something like~~

[outdated]

**Comment by parkan** [comment]
(ok, this appears to be for an old protobuf version, looking for updated solution)

**Comment by parkan** [comment]
Ok so you can use `oneof` but there's basically no way for the "imported"/"inherited" properties to be flat at the same level as the directly defined properties. So is the solution to just define everything directly?

**Comment by parkan** [comment]
Ok it seems like the way to do this is just 

```
EntityChainCell =
   <EntityUpdateCell>
 | <EntityLinkCell>
 | <Nil>

EntityUpdateCell = {
 "type" : "entityUpdate"
 "chain" : <Reference>
 "entity" : <Reference>
 "signatures" : <Signatures>
  <Key> : <Value> ... ; metadata updates
 }
```

```
message EntityUpdateCell {
  required Type type = 1;
  required Ref chain = 2;
  required Ref entity = 3;
  repeated Signature signatures = 4;
  repeated Metadata metadata = 5; // or map<string, Any> metadata = 5;
}

message EntityChainCell {
  oneof cell {
    EntityUpdateCell entityUpdateCell = 1;
    EntityLinkCell entityLinkCell = 2;
    // ...
  }
}
```

One corollary seems to be that you cannot define a variable number of fields at the top level (without packing into a `repeated` or `map`) so having the metadata update kv pairs there is not possible if we want to serialize to protobuf.

**Comment by parkan** [comment]
Though FWIW this is what IPLD protobuf looks like:

``` proto
package ipldpb;

import "code.google.com/p/gogoprotobuf/gogoproto/gogo.proto";

option (gogoproto.gostring_all) = true;
option (gogoproto.equal_all) = true;
option (gogoproto.verbose_equal_all) = true;
option (gogoproto.goproto_stringer_all) = false;
option (gogoproto.stringer_all) =  true;
option (gogoproto.populate_all) = true;
option (gogoproto.testgen_all) = true;
option (gogoproto.benchgen_all) = true;
option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;

// An IPFS MerkleDAG Link
message PBLink {

  // multihash of the target object
  optional bytes Hash = 1;

  // utf string name. should be unique per object
  optional string Name = 2;

  // cumulative size of target object
  optional uint64 Tsize = 3;
}

// An IPFS MerkleDAG Node
message PBNode {

  // refs to other objects
  repeated PBLink Links = 2;

  // opaque user data
  optional bytes Data = 1;
}
```

(from https://github.com/ipfs/go-ipld/blob/master/coding/pb/ipld.proto)

So maybe we just ride on top of this.

**Comment by yusefnapora** [comment]
Per our discussion in slack:

Rather than having unique protobuf message types for every mediachain datatype, we could encode the mediachain types to CBOR and pass them around in the `Data` field of the `PBNode` type listed above.

#### Advantages
- compatible with existing IPFS data structures
- maps closely to the future IPLD canonical CBOR format
- reduces the amount of generated code from protobufs
- we already have a JVM CBOR serializer for json4s `JValue` types
- pushes polymorphism from protobuf to the CBOR serialization / deserialization phase

The last is relevant because protobuf has fairly limited support for polymorphism; you can either use a `oneof` field, or use `Any` as the field type. 

The data model described in the [rfc](https://github.com/mediachain/mediachain/blob/master/rfc/mediachain-rfc-1.md) is basically a tagged union, dispatched on the `type` field.  The CBOR de-serialization code could pretty easily inspect the `type` field when decoding, and we could go from there to domain model types.

#### Downsides
- all clients / peers need to implement the CBOR serialization code
- we basically end up with one data type on the wire, `PBNode`, with all the semantics packed into the opaque `Data` field.   

If we go this route, we should probably wrap `PBNode` in thin wrappers, e.g.

``` protobuf
message ChainCell {
  PBNode value = 1;
}
```

So that our service endpoints can indicate what type of data structure they expect.  It will still be on the client to extract and validate the CBOR from the `value.Data` field.

#### Questions
- How stable is the current ipfs protobuf format?  Looks like it's probably going to be supported for a while...
- How closely will our CBOR representation map to the final IPLD spec?
- Does this make versioning / modifying our data types harder or easier?

@jbenet, if you have any input on this idea, that would be much appreciated!

**Comment by parkan** [comment]
I suspect we might be better off just roundtripping the CBOR inside a `bytes` instead of using the `PBNode` message, because we don't need backwards compatibility with pre-IPLD merkledag format. Would love to hear from @jbenet though :wave:

**Comment by parkan** [comment]
Or maybe @whyrusleeping or @mildred?

**Comment by yusefnapora** [comment]
Yeah, that makes sense.  Using the merlkedag protobufs only seems worth it if we take advantage of the `Links` field.  But I don't think we need that at the moment.

**Comment by parkan** [comment]
I think that's only really there for the old format backwards comp, but I'm not sure

**Comment by whyrusleeping** [comment]
@jbenet is gonna be the best one to answer most of these questions, but as for the current ipfs protobuf format, we will be supporting it (as far as i'm concerned) indefinitely

**Comment by yusefnapora** [comment]
thanks @whyrusleeping!

my understanding is that the current protobufs are the foundation for all of the existing IPFS linked structures (e.g. the filesystem bits, etc).  So it makes sense that you'd want that to keep working :)

**Comment by whyrusleeping** [comment]
that is correct :)

**Comment by parkan** [comment]
Ok what do we think about renaming this to `protocol`, with structure such as this:

```
protocol
|--core (RFC types)
    |--Types.scala (from mediachain/transactor)
    `--TypeSerialization.scala (??? + dependencies?)
|--cluster (cluster queries and commands)
    `--Types.scala (from mediachain/transactor)
`--client (client protobuf interfaces)
    |--Types.proto (from L-SPACE + mediachain-cli, currently in there)
    `--Services.proto
```

**Comment by vyzo** [comment]
Is it a good idea  to detach internal cluster types from their implementation?
They are kind of an internal implementation detail, at least for copycat.

**Comment by parkan** [comment]
@vyzo but clients need to see them, no? (e.g. I need to create and serialize a `JournalInsert` to do a write, or to receive and deserialize a `JournalUpdate` to get syndication)

**Comment by vyzo** [comment]
@parkan that's a good point - they need to see the notification messages at the very least.

**Comment by parkan** [comment]
This now lives in https://github.com/mediachain/mediachain/tree/master/protocol

Will need to extract this as a subtree and update https://github.com/mediachain/protos but closing for now
